export type ReviewerGender = "male" | "female";

/** Hair / silhouette variants within a gender (picked by name hash). */
export type ReviewerHairVariant = "a" | "b" | "c";

export type ReviewerPersona = {
  gender: ReviewerGender;
  variant: ReviewerHairVariant;
};

/** First names that map to a feminine silhouette. */
const FEMALE_FIRST_NAMES = new Set([
  "maya",
  "priya",
  "elena",
  "anna",
  "anne",
  "emma",
  "olivia",
  "sophia",
  "sofia",
  "mia",
  "ava",
  "isabella",
  "emily",
  "amelia",
  "harper",
  "evelyn",
  "abigail",
  "elizabeth",
  "ella",
  "scarlett",
  "grace",
  "chloe",
  "victoria",
  "riley",
  "aria",
  "lily",
  "natalie",
  "zoe",
  "zoey",
  "hannah",
  "leah",
  "sarah",
  "sara",
  "rachel",
  "rebecca",
  "jessica",
  "jennifer",
  "lauren",
  "amanda",
  "nicole",
  "stephanie",
  "michelle",
  "kimberly",
  "ashley",
  "megan",
  "katie",
  "kate",
  "maria",
  "lucia",
  "carmen",
  "ines",
  "noa",
  "tamar",
  "yael",
  "michal",
  "shira",
  "roni",
  "dana",
  "tal",
  "gal",
  "orit",
  "nina",
  "ira",
  "vera",
  "olga",
  "katya",
  "yulia",
  "svetlana",
  "marina",
  "daria",
  "anastasia",
  "fatima",
  "aisha",
  "layla",
  "nour",
  "mira",
  "sana",
  "lin",
  "mei",
  "yuki",
  "hana",
  "sakura",
]);

/** First names that map to a masculine silhouette. */
const MALE_FIRST_NAMES = new Set([
  "jordan",
  "sam",
  "chris",
  "christopher",
  "james",
  "john",
  "robert",
  "michael",
  "david",
  "william",
  "richard",
  "joseph",
  "thomas",
  "charles",
  "daniel",
  "matthew",
  "anthony",
  "mark",
  "donald",
  "steven",
  "paul",
  "andrew",
  "joshua",
  "kenneth",
  "kevin",
  "brian",
  "george",
  "timothy",
  "ronald",
  "edward",
  "jason",
  "jeffrey",
  "ryan",
  "jacob",
  "gary",
  "nicholas",
  "eric",
  "jonathan",
  "stephen",
  "larry",
  "justin",
  "scott",
  "brandon",
  "benjamin",
  "samuel",
  "raymond",
  "gregory",
  "frank",
  "alexander",
  "patrick",
  "jack",
  "dennis",
  "jerry",
  "tyler",
  "aaron",
  "jose",
  "adam",
  "nathan",
  "henry",
  "douglas",
  "zachary",
  "peter",
  "kyle",
  "noah",
  "ethan",
  "jeremy",
  "walter",
  "christian",
  "keith",
  "roger",
  "terry",
  "austin",
  "sean",
  "gerald",
  "carl",
  "harold",
  "dylan",
  "jesse",
  "bryan",
  "lawrence",
  "arthur",
  "gabriel",
  "bruce",
  "logan",
  "albert",
  "willie",
  "alan",
  "juan",
  "wayne",
  "ralph",
  "roy",
  "eugene",
  "randy",
  "vincent",
  "russell",
  "louis",
  "philip",
  "bobby",
  "johnny",
  "bradley",
  "amir",
  "omar",
  "hassan",
  "youssef",
  "ahmed",
  "ali",
  "wei",
  "chen",
  "hiro",
  "kenji",
  "ivan",
  "dmitri",
  "sergey",
  "alexei",
  "pavel",
  "guy",
  "avi",
  "yonatan",
  "yoni",
  "itay",
  "idan",
  "omer",
  "erez",
  "asaf",
  "nir",
  "roi",
  "lior",
]);

const VARIANTS: readonly ReviewerHairVariant[] = ["a", "b", "c"];

function hashName(value: string): number {
  let hash = 0;
  for (let i = 0; i < value.length; i += 1) {
    hash = (hash * 31 + value.charCodeAt(i)) >>> 0;
  }
  return hash;
}

function firstToken(fullName: string): string {
  return fullName.trim().split(/\s+/)[0]?.toLowerCase() ?? "";
}

/**
 * Pick a faceless guy/girl silhouette from the reviewer display name.
 * Known first names win; otherwise hash the name (stable, not random).
 */
export function resolveReviewerPersona(fullName: string): ReviewerPersona {
  const key = fullName.trim().toLowerCase();
  const first = firstToken(fullName);
  const hash = hashName(key || first || "reviewer");

  let gender: ReviewerGender;
  if (FEMALE_FIRST_NAMES.has(first)) gender = "female";
  else if (MALE_FIRST_NAMES.has(first)) gender = "male";
  else gender = hash % 2 === 0 ? "male" : "female";

  const variant = VARIANTS[hash % VARIANTS.length] ?? "a";
  return { gender, variant };
}
