import { toolsList } from "@/data/tools";
import type { HomeAudioToolIconKey } from "@/lib/tool-module";
import {
  ArrowLeftRight,
  AudioLines,
  Binary,
  BookOpen,
  Braces,
  CalendarRange,
  Clock,
  Code,
  CodeXml,
  Combine,
  Copy,
  Crop,
  Database,
  Dices,
  Disc3,
  Eraser,
  Expand,
  EyeOff,
  File,
  FileAudio,
  FileCode,
  FileImage,
  FileJson,
  FileMusic,
  FileText,
  FileType2,
  Fingerprint,
  Gauge,
  GitCompare,
  Globe,
  Hash,
  ImageDown,
  KeyRound,
  Layers,
  LetterText,
  Link as LinkIcon,
  ListOrdered,
  Minimize2,
  Music,
  PanelTop,
  Palette,
  PenLine,
  Pipette,
  Presentation,
  QrCode,
  Receipt,
  RotateCw,
  Scale,
  Scissors,
  Settings,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Split,
  SquarePen,
  Stamp,
  Table,
  Tags,
  Trash2,
  Unlock,
  Video,
  Volume2,
  VolumeX,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const LUCIDE_BY_KEY = {
  expand: Expand,
  "file-image": FileImage,
  "file-text": FileText,
  crop: Crop,
  "rotate-cw": RotateCw,
  "minimize-2": Minimize2,
  "image-down": ImageDown,
  sparkles: Sparkles,
  "file-code": FileCode,
  layers: Layers,
  smartphone: Smartphone,
  pipette: Pipette,
  braces: Braces,
  table: Table,
  "file-json": FileJson,
  binary: Binary,
  link: LinkIcon,
  "git-compare": GitCompare,
  eraser: Eraser,
  dices: Dices,
  "code-xml": CodeXml,
  "letter-text": LetterText,
  globe: Globe,
  "qr-code": QrCode,
  "key-round": KeyRound,
  hash: Hash,
  fingerprint: Fingerprint,
  "shield-check": ShieldCheck,
  scale: Scale,
  clock: Clock,
  "book-open": BookOpen,
  gauge: Gauge,
  "file-type-2": FileType2,
  "arrow-left-right": ArrowLeftRight,
  database: Database,
  music: Music,
  "file-audio": FileAudio,
  scissors: Scissors,
  "audio-waveform": AudioLines,
  disc: Disc3,
  "file-music": FileMusic,
  "volume-2": Volume2,
  tags: Tags,
  "panel-top": PanelTop,
  palette: Palette,
  "eye-off": EyeOff,
  "pen-line": PenLine,
  stamp: Stamp,
  video: Video,
} satisfies Record<string, LucideIcon>;

const SLUG_ICON_KEYS: Record<string, keyof typeof LUCIDE_BY_KEY> = {
  "resize-image": "expand",
  "convert-to-png": "file-image",
  "crop-image": "crop",
  "rotate-image": "rotate-cw",
  "compress-image": "minimize-2",
  "heic-to-jpg": "image-down",
  "webp-to-jpg": "image-down",
  "svg-to-png": "file-image",
  "image-grayscale": "eye-off",
  "flip-image": "arrow-left-right",
  "image-metadata-editor": "tags",
  "image-metadata-wiper": "eye-off",
  "image-dpi-converter": "gauge",
  "image-optimizer": "minimize-2",
  "paint-on-image": "pen-line",
  "image-blur-redact": "eye-off",
  "image-watermark": "stamp",
  "image-grid-splitter": "crop",
  "favicon-generator": "sparkles",
  "generate-favicon": "sparkles",
  "png-to-ico": "file-image",
  "ico-to-png": "image-down",
  "svg-to-favicon": "braces",
  "favicon-pack": "layers",
  "apple-touch-icon": "smartphone",
  "favicon-compressor": "minimize-2",
  "favicon-cropper": "crop",
  "transparent-favicon": "pipette",
  "favicon-code-generator": "braces",
  "favicon-previewer": "panel-top",
  "json-formatter": "braces",
  "json-csv-explorer": "table",
  "json-to-csv": "table",
  "json-minifier": "minimize-2",
  "csv-to-json": "file-json",
  "base64-encoder-decoder": "binary",
  "url-encoder-decoder": "link",
  "url-parameter-stripper": "link",
  "text-diff-checker": "git-compare",
  "text-diff": "git-compare",
  "text-sanitizer": "eraser",
  "text-workspace": "file-text",
  "string-generator": "dices",
  "html-markdown-converter": "code-xml",
  "word-character-counter": "letter-text",
  "user-agent-parser": "globe",
  "qr-code-generator": "qr-code",
  "jwt-debugger": "key-round",
  "yaml-json-converter": "arrow-left-right",
  "csv-to-markdown-table": "table",
  "sql-query-formatter": "database",
  "password-generator": "key-round",
  "hash-generator": "hash",
  "uuid-generator": "fingerprint",
  "ssl-decoder": "shield-check",
  "color-palette-extractor": "pipette",
  "color-converter": "palette",
  "unit-converter": "scale",
  "timezone-converter": "clock",
  "reading-time-calculator": "book-open",
  "readability-analyzer": "gauge",
  "lorem-ipsum-generator": "letter-text",
  "mp3-tools-hub": "file-audio",
  "mp4-tools-hub": "video",
  "video-tools-hub": "video",
  "developer-tools-hub": "key-round",
  "png-tools-hub": "file-image",
  "jpg-tools-hub": "file-image",
  "extract-tools-hub": "scissors",
  "text-tools-hub": "letter-text",
  "compress-tools-hub": "minimize-2",
  "convert-tools-hub": "arrow-left-right",
  "pdf-tools-hub": "file-text",
  "favicon-tools-hub": "sparkles",
  "json-tools-hub": "braces",
  "yaml-tools-hub": "file-code",
  "xml-tools-hub": "code-xml",
  "case-converter": "file-type-2",
};

for (const tool of toolsList) {
  SLUG_ICON_KEYS[tool.id] = tool.iconKey as HomeAudioToolIconKey;
}

const PDF_TOOL_LUCIDE: Record<string, LucideIcon> = {
  "pdf-merge": Combine,
  "pdf-compress": Minimize2,
  "pdf-split": Split,
  "pdf-to-booklet": BookOpen,
  "compare-pdf": GitCompare,
  "batch-rename-pdf": Tags,
  "pdf-text-editor": SquarePen,
  "pdf-editor": SquarePen,
  "annotate-pdf": PenLine,
  "reorder-pdf-pages": ListOrdered,
  "extract-pdf-pages": Copy,
  "jpg-to-pdf": FileImage,
  "png-to-pdf": FileImage,
  "heic-to-pdf": FileImage,
  "pdf-to-jpg": FileImage,
  "pdf-to-png": FileImage,
  "pdf-to-text": FileText,
  "extract-images": FileImage,
  "word-to-pdf": FileText,
  "pdf-to-word": FileType2,
  "pdf-to-excel": Table,
  "excel-to-pdf": Table,
  "pdf-to-powerpoint": Presentation,
  "powerpoint-to-pdf": Presentation,
  "protect-pdf": ShieldCheck,
  "pdf-password-recovery": KeyRound,
  "unlock-pdf": Unlock,
  "remove-hidden-metadata": EyeOff,
  "flatten-pdf": Layers,
  "repair-pdf": Wrench,
  "redact-pdf": Eraser,
  "rotate-pdf": RotateCw,
  "crop-pdf": Crop,
  "sign-pdf": PenLine,
  "autocad-to-pdf": FileCode,
  "openoffice-to-pdf": FileText,
  "markdown-to-pdf": FileCode,
  "html-to-pdf": CodeXml,
  "ebook-to-pdf": BookOpen,
  "iwork-to-pdf": FileText,
  "custom-paper-margin": Expand,
  "safe-to-share-auditor": ShieldCheck,
  "add-page-numbers": Hash,
  "add-watermark": Stamp,
  "delete-pdf-pages": Trash2,
  "n-up-pdf": Layers,
  "grayscale-pdf": ImageDown,
  "pdf-a-converter": FileType2,
  "pdf-linearization": Gauge,
  "pdf-to-epub": BookOpen,
  "pdf-to-xps": FileCode,
  "pdf-to-html": CodeXml,
  "extract-tables-pdf": Table,
  "pdf-metadata-editor": Tags,
  "pdf-signature-validator": ShieldCheck,
  "invoice-generator": Receipt,
  "timeline-gantt-generator": CalendarRange,
  "data-converter-visualizer": Database,
  "video-compressor": Minimize2,
  "video-resizer": Expand,
  "video-rotator": RotateCw,
  "video-to-mp4": Video,
  "video-converter": ArrowLeftRight,
  "video-to-gif": Video,
  "video-trimmer": Scissors,
  "video-speed-controller": Gauge,
  "video-speed": Gauge,
  "video-to-mp3": Music,
  "video-muter": VolumeX,
  "video-metadata-cleaner": ShieldCheck,
  default: FileText,
};

const SLUG_RESOLVERS: { test: (s: string) => boolean; key: string }[] = [
  { test: (s) => s.includes("delete-pdf-pages"), key: "delete-pdf-pages" },
  { test: (s) => s.includes("add-page-numbers"), key: "add-page-numbers" },
  { test: (s) => s.includes("add-watermark"), key: "add-watermark" },
  { test: (s) => s.includes("pdf-to-powerpoint"), key: "pdf-to-powerpoint" },
  { test: (s) => s.includes("powerpoint-to-pdf"), key: "powerpoint-to-pdf" },
  { test: (s) => s.includes("pdf-to-excel"), key: "pdf-to-excel" },
  { test: (s) => s.includes("excel-to-pdf"), key: "excel-to-pdf" },
  { test: (s) => s.includes("pdf-to-word"), key: "pdf-to-word" },
  { test: (s) => s.includes("pdf-to-text"), key: "pdf-to-text" },
  { test: (s) => s.includes("extract-images"), key: "extract-images" },
  { test: (s) => s.includes("word-to-pdf"), key: "word-to-pdf" },
  { test: (s) => s.includes("invoice-generator"), key: "invoice-generator" },
  { test: (s) => s.includes("timeline-gantt"), key: "timeline-gantt-generator" },
  { test: (s) => s.includes("data-converter"), key: "data-converter-visualizer" },
  { test: (s) => s.includes("protect-pdf"), key: "protect-pdf" },
  { test: (s) => s.includes("pdf-password-recovery"), key: "pdf-password-recovery" },
  { test: (s) => s.includes("unlock-pdf"), key: "unlock-pdf" },
  { test: (s) => s.includes("remove-hidden-metadata"), key: "remove-hidden-metadata" },
  { test: (s) => s.includes("flatten-pdf"), key: "flatten-pdf" },
  { test: (s) => s.includes("repair-pdf"), key: "repair-pdf" },
  { test: (s) => s.includes("redact-pdf"), key: "redact-pdf" },
  { test: (s) => s.includes("rotate-pdf"), key: "rotate-pdf" },
  { test: (s) => s.includes("crop-pdf"), key: "crop-pdf" },
  { test: (s) => s.includes("sign-pdf"), key: "sign-pdf" },
  { test: (s) => s.includes("autocad-to-pdf"), key: "autocad-to-pdf" },
  { test: (s) => s.includes("openoffice-to-pdf"), key: "openoffice-to-pdf" },
  { test: (s) => s.includes("markdown-to-pdf"), key: "markdown-to-pdf" },
  { test: (s) => s.includes("html-to-pdf"), key: "html-to-pdf" },
  { test: (s) => s.includes("ebook-to-pdf"), key: "ebook-to-pdf" },
  { test: (s) => s.includes("iwork-to-pdf"), key: "iwork-to-pdf" },
  { test: (s) => s.includes("heic-to-pdf"), key: "heic-to-pdf" },
  { test: (s) => s.includes("png-to-pdf"), key: "png-to-pdf" },
  { test: (s) => s.includes("jpg-to-pdf"), key: "jpg-to-pdf" },
  { test: (s) => s.includes("pdf-to-png"), key: "pdf-to-png" },
  { test: (s) => s.includes("pdf-to-jpg"), key: "pdf-to-jpg" },
  { test: (s) => s.includes("pdf-compress"), key: "pdf-compress" },
  { test: (s) => s.includes("custom-paper-margin"), key: "custom-paper-margin" },
  { test: (s) => s.includes("safe-to-share-auditor"), key: "safe-to-share-auditor" },
  { test: (s) => s.includes("pdf-to-booklet"), key: "pdf-to-booklet" },
  { test: (s) => s.includes("compare-pdf"), key: "compare-pdf" },
  { test: (s) => s.includes("batch-rename-pdf"), key: "batch-rename-pdf" },
  { test: (s) => s.includes("pdf-editor"), key: "pdf-editor" },
  { test: (s) => s.includes("pdf-text-editor"), key: "pdf-text-editor" },
  { test: (s) => s.includes("annotate-pdf"), key: "annotate-pdf" },
  { test: (s) => s.includes("reorder-pdf-pages"), key: "reorder-pdf-pages" },
  { test: (s) => s.includes("extract-pdf-pages"), key: "extract-pdf-pages" },
  { test: (s) => s.includes("pdf-split"), key: "pdf-split" },
  { test: (s) => s.includes("pdf-merge"), key: "pdf-merge" },
  { test: (s) => s.includes("video-compressor"), key: "video-compressor" },
  { test: (s) => s.includes("video-resizer"), key: "video-resizer" },
  { test: (s) => s.includes("video-rotator"), key: "video-rotator" },
  { test: (s) => s.includes("video-to-mp4"), key: "video-to-mp4" },
  { test: (s) => s.includes("video-converter"), key: "video-converter" },
  { test: (s) => s.includes("video-to-gif"), key: "video-to-gif" },
  { test: (s) => s.includes("video-trimmer"), key: "video-trimmer" },
  { test: (s) => s.includes("video-speed-controller"), key: "video-speed-controller" },
  { test: (s) => s.includes("video-speed"), key: "video-speed" },
  { test: (s) => s.includes("video-to-mp3"), key: "video-to-mp3" },
  { test: (s) => s.includes("video-muter"), key: "video-muter" },
  { test: (s) => s.includes("video-metadata-cleaner"), key: "video-metadata-cleaner" },
];

function resolveToolKey(slug?: string, label?: string): string {
  const source = `${slug || ""} ${label || ""}`.toLowerCase();
  for (const { test, key } of SLUG_RESOLVERS) {
    if (test(source)) return key;
  }
  return "default";
}

function inferLucideFromText(slug?: string, label?: string): LucideIcon {
  const source = `${slug || ""} ${label || ""}`.toLowerCase();

  if (/video|mp4|gif/.test(source)) return Video;
  if (/audio|mp3|wav|flac|ogg|m4a/.test(source)) return FileAudio;
  if (/image|jpg|jpeg|png|ico|svg|heic|favicon|crop|resize/.test(source)) return FileImage;
  if (/json|yaml|csv|sql|code|developer|jwt|base64|markdown|html/.test(source)) return Code;
  if (/security|password|protect|unlock|hash|uuid|shield|redact|metadata/.test(source)) return ShieldCheck;
  if (/compress|minify|optim/.test(source)) return Minimize2;
  if (/convert|transcode|to-/.test(source)) return ArrowLeftRight;
  if (/merge|combine|join/.test(source)) return Combine;
  if (/split|extract|trim/.test(source)) return Split;
  if (/sign|annotate|edit|watermark/.test(source)) return PenLine;
  if (/setting|config/.test(source)) return Settings;

  return File;
}

/** Neutral Lucide icon for any tool slug — never returns null. */
export function getToolListLucideIcon(slug?: string, label?: string): LucideIcon {
  if (slug && SLUG_ICON_KEYS[slug]) {
    const mapped = LUCIDE_BY_KEY[SLUG_ICON_KEYS[slug]];
    if (mapped) return mapped;
  }

  const resolvedKey = resolveToolKey(slug, label);
  if (PDF_TOOL_LUCIDE[resolvedKey]) return PDF_TOOL_LUCIDE[resolvedKey];

  if (slug && PDF_TOOL_LUCIDE[slug]) return PDF_TOOL_LUCIDE[slug];

  return inferLucideFromText(slug, label);
}

/** @deprecated Use getToolListLucideIcon — kept for transitional imports. */
export function getCategoryDirectoryLucideIcon(slug?: string): LucideIcon {
  return getToolListLucideIcon(slug);
}
