import type { Metadata } from "next";
export const runtime = "edge";
import Link from "next/link";
import { CompactToolCardGrid } from "@/components/CompactToolCardGrid";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { buildDefaultSocialImages } from "@/lib/og-images";
import { JsonLd } from "@/lib/schema";
import { registry } from "@/lib/registry";
import { absoluteUrl } from "@/lib/site";

type Props = { params: Promise<{ locale: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params;
  const title = "Privacy-first PDF tools";
  const description =
    "A hub page for teams that need PDF utilities without routing confidential files through unknown servers.";
  const social = buildDefaultSocialImages(locale, { alt: title });

  return {
    title,
    description,
    alternates: { canonical: `/${locale}/privacy-first-pdf-tools/` },
    openGraph: {
      title,
      description,
      url: absoluteUrl(`/${locale}/privacy-first-pdf-tools/`),
      ...social.openGraph,
    },
    twitter: {
      title,
      description,
      ...social.twitter,
    },
  };
}

export default async function PillarPage({ params }: Props) {
  await params;
  const featuredSlugs = ["pdf-merge", "pdf-compress", "pdf-split", "jpg-to-pdf"];
  const featuredTools = featuredSlugs
    .map((slug) => registry.tools.find((tool) => tool.slug === slug))
    .filter((tool): tool is (typeof registry.tools)[number] => Boolean(tool));

  return (
    <>
      <JsonLd
        data={{
          "@context": "https://schema.org",
          "@type": "CollectionPage",
          name: "Privacy-first PDF tools",
          url: absoluteUrl("/privacy-first-pdf-tools/"),
        }}
      />
      <SiteHeader />
      <main className="mx-auto max-w-4xl space-y-3 px-4 py-10 text-black dark:text-neutral-200 dark:text-black dark:text-neutral-200 md:px-4">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-black dark:text-neutral-200">Pillar guide</p>
        <h1 className="text-3xl font-bold text-black dark:text-neutral-200 dark:text-white md:text-4xl">Privacy-first PDF tools</h1>
        <p>
          If your policy says “no random cloud converters,” you still need to merge invoices, shrink attachments, and
          split contracts. JoinMyPDF keeps those operations{" "}
          <Link className="text-black dark:text-neutral-200 hover:underline" href="/privacy/">
            on your device
          </Link>{" "}
          while preserving a premium, straightforward interface.
        </p>
        <CompactToolCardGrid
          items={featuredTools.map((tool) => ({
            href: `/tools/${tool.slug}/`,
            label: tool.title,
            slugHint: tool.slug,
          }))}
        />
        <p>
          Pair these tools with our <Link href="/blog/">guides</Link> when you need a documented workflow for your
          team—not a wall of autogenerated keyword pages.
        </p>
      </main>
      <SiteFooter />
    </>
  );
}
