import type { Metadata } from "next";
export { runtime } from "@/lib/cloudflare-runtime";
import Link from "next/link";
import { CompactToolCardGrid } from "@/components/CompactToolCardGrid";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { JsonLd } from "@/lib/schema";
import { registry } from "@/lib/registry";
import { absoluteUrl } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy-first PDF tools",
  description:
    "A hub page for teams that need PDF utilities without routing confidential files through unknown servers.",
  alternates: { canonical: "/privacy-first-pdf-tools/" },
};

export default function PillarPage() {
  const featuredSlugs = ["pdf-merge", "pdf-compress", "pdf-split", "jpg-to-pdf"];
  const featuredTools = featuredSlugs
    .map((slug) => registry.tools.find((tool) => tool.slug === slug))
    .filter((tool): tool is (typeof registry.tools)[number] => Boolean(tool));

  return (
    <>
      <JsonLd
        data={{
          "@context": "https://schema.org",
          "@type": "CollectionPage",
          name: "Privacy-first PDF tools",
          url: absoluteUrl("/privacy-first-pdf-tools/"),
        }}
      />
      <SiteHeader />
      <main className="mx-auto max-w-4xl space-y-6 px-4 py-10 text-slate-700 dark:text-slate-300 md:px-6">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">Pillar guide</p>
        <h1 className="text-3xl font-bold text-slate-900 dark:text-white md:text-4xl">Privacy-first PDF tools</h1>
        <p>
          If your policy says “no random cloud converters,” you still need to merge invoices, shrink attachments, and
          split contracts. JoinMyPDF keeps those operations{" "}
          <Link className="text-brand hover:underline" href="/privacy/">
            on your device
          </Link>{" "}
          while preserving a premium, straightforward interface.
        </p>
        <CompactToolCardGrid
          items={featuredTools.map((tool) => ({
            href: `/tools/${tool.slug}/`,
            label: tool.title,
            slugHint: tool.slug,
          }))}
        />
        <p>
          Pair these tools with our <Link href="/blog/">guides</Link> when you need a documented workflow for your
          team—not a wall of autogenerated keyword pages.
        </p>
      </main>
      <SiteFooter />
    </>
  );
}
