import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { JsonLd } from "@/lib/schema";
import { absoluteUrl } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy-first PDF tools",
  description:
    "A hub page for teams that need PDF utilities without routing confidential files through unknown servers.",
  alternates: { canonical: "/privacy-first-pdf-tools/" },
};

export default function PillarPage() {
  return (
    <>
      <JsonLd
        data={{
          "@context": "https://schema.org",
          "@type": "CollectionPage",
          name: "Privacy-first PDF tools",
          url: absoluteUrl("/privacy-first-pdf-tools/"),
        }}
      />
      <SiteHeader />
      <main className="mx-auto max-w-3xl space-y-6 px-4 py-10 text-ink-muted md:px-6">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">Pillar guide</p>
        <h1 className="text-3xl font-bold text-ink md:text-4xl">Privacy-first PDF tools</h1>
        <p>
          If your policy says “no random cloud converters,” you still need to merge invoices, shrink attachments, and
          split contracts. JoinMyPDF keeps those operations{" "}
          <Link className="text-brand hover:underline" href="/privacy/">
            on your device
          </Link>{" "}
          while preserving a premium, straightforward interface.
        </p>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <Link className="text-brand hover:underline" href="/tools/pdf-merge/">
              Merge PDFs
            </Link>{" "}
            for board packs, HR bundles, and client submissions.
          </li>
          <li>
            <Link className="text-brand hover:underline" href="/tools/pdf-compress/">
              Compress PDFs
            </Link>{" "}
            when portals or email reject large attachments.
          </li>
          <li>
            <Link className="text-brand hover:underline" href="/tools/pdf-split/">
              Split PDFs
            </Link>{" "}
            to isolate signed pages or share only the relevant sections.
          </li>
          <li>
            <Link className="text-brand hover:underline" href="/tools/jpg-to-pdf/">
              Images → PDF
            </Link>{" "}
            for receipts, field photos, and scans.
          </li>
        </ul>
        <p>
          Pair these tools with our <Link href="/blog/">guides</Link> when you need a documented workflow for your
          team—not a wall of autogenerated keyword pages.
        </p>
      </main>
      <SiteFooter />
    </>
  );
}
