import { NextResponse } from 'next/server';
import { jsPDF } from 'jspdf';

// פונקציית עזר להוספת Footer פרסומי לכל עמוד
const addFooter = (doc: any) => {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text(
      "Generated by WattQuick | Manage, Edit, and Convert PDFs at JoinMyPDF.com",
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.link(50, doc.internal.pageSize.getHeight() - 15, 110, 10, { url: 'https://joinmypdf.com' });
  }
};

// פונקציית עזר להגדרת צבעים לפי תוכן התוצאה
const getStatusColor = (value: string | number) => {
  const val = String(value).toLowerCase();
  if (val.includes("error") || val.includes("danger") || val.includes("high")) return [220, 53, 69]; // אדום
  if (val.includes("warning") || val.includes("check")) return [255, 193, 7]; // צהוב
  if (val.includes("efficiency") || val.includes("ok") || val.includes("success")) return [40, 167, 69]; // ירוק
  return [0, 0, 0]; // שחור ברירת מחדל
};

export async function OPTIONS() {
  return new NextResponse(null, {
    status: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    },
  });
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { calculatorName, inputs, results } = body;

    const doc = new jsPDF();

    // כותרת
    doc.setFontSize(20);
    doc.setTextColor(0, 0, 0);
    doc.text(`WattQuick Report: ${calculatorName}`, 20, 20);
    
    // Inputs
    doc.setFontSize(12);
    doc.text("Inputs & Calculation Data:", 20, 40);
    doc.setLineWidth(0.5);
    doc.line(20, 42, 190, 42);

    let y = 55;
    Object.entries(inputs || {}).forEach(([key, value]) => {
      doc.setTextColor(0, 0, 0);
      doc.text(`${key}: ${String(value)}`, 20, y);
      y += 10;
    });

    // Results
    y += 10;
    doc.setFontSize(14);
    doc.text("Results:", 20, y);
    doc.setFontSize(12);
    y += 10;
    
    Object.entries(results || {}).forEach(([key, value]) => {
      // במקום מה שהיה שם, שנה לזה:
const color = getStatusColor(String(value)); // המרה מפורשת ל-string
      doc.setTextColor(color[0], color[1], color[2]);
      doc.text(`${key}: ${String(value)}`, 20, y);
      y += 10;
    });

    // הוספת ה-Footer
    addFooter(doc);

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="wattquick-report.pdf"`,
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Content-Type',
      },
    });
  } catch (error) {
    console.error("PDF Generation Error:", error);
    return NextResponse.json({ error: 'Failed to generate PDF' }, { 
      status: 500,
      headers: { 'Access-Control-Allow-Origin': '*' }
    });
  }
}