import { NextResponse } from 'next/server';
import { jsPDF } from 'jspdf';

export const runtime = 'edge';

const getAllowedHeaders = (origin: string | null) => {
  const allowedOrigins = [
    'https://wattquick.com',
    'https://calnexapp.com',
  ];

  const isAllowed =
    origin && allowedOrigins.includes(origin);

  return {
    'Access-Control-Allow-Origin': isAllowed
      ? origin
      : '',
    'Access-Control-Allow-Methods':
      'GET, POST, OPTIONS',
    'Access-Control-Max-Age': '86400',
    'Access-Control-Allow-Headers':
      'Content-Type, Authorization',
  };
};

const addFooter = (doc: any) => {
  const pageCount = doc.internal.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    doc.setDrawColor(220, 220, 220);
    doc.line(
      15,
      doc.internal.pageSize.getHeight() - 18,
      195,
      doc.internal.pageSize.getHeight() - 18
    );

    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);

    doc.text(
      `Generated by WattQuick | Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
};

const getStatusColor = (value: string | number) => {
  const val = String(value).toLowerCase();

  if (val.includes('$')) {
    return [0, 102, 204];
  }

  if (val.includes('%')) {
    return [40, 167, 69];
  }

  if (
    val.includes('w') ||
    val.includes('wh') ||
    val.includes('kw') ||
    val.includes('v') ||
    val.includes('ah')
  ) {
    return [255, 140, 0];
  }

  return [60, 60, 60];
};

export async function OPTIONS(req: Request) {
  const origin = req.headers.get('origin');

  return new NextResponse(null, {
    status: 200,
    headers: getAllowedHeaders(origin),
  });
}

export async function POST(req: Request) {
  const origin = req.headers.get('origin');
  const headers = getAllowedHeaders(origin);

  try {
    const body = await req.json();

    const {
      calculatorName = 'Calculator',
      inputs = {},
      results = {},
    } = body;

    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    let y = 0;

    // ==========================
    // HEADER
    // ==========================

    doc.setFillColor(0, 102, 204);
    doc.rect(0, 0, pageWidth, 32, 'F');

    doc.setTextColor(255, 255, 255);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('WattQuick Report', 15, 15);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.text(calculatorName, 15, 24);

    y = 45;

    // ==========================
    // INPUTS SECTION
    // ==========================

    doc.setTextColor(0, 0, 0);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(15);
    doc.text('Inputs', 15, y);

    doc.setDrawColor(0, 102, 204);
    doc.setLineWidth(0.5);
    doc.line(15, y + 2, 195, y + 2);

    y += 12;

    Object.entries(inputs).forEach(([key, value]) => {
      const text = `${key}: ${String(value)}`;

      const lines = doc.splitTextToSize(text, 170);

      if (y + lines.length * 6 > 270) {
        doc.addPage();
        y = 20;
      }

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.text(lines, 20, y);

      y += lines.length * 6 + 2;
    });

    y += 10;

    // ==========================
    // RESULTS SECTION
    // ==========================

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(15);
    doc.text('Results', 15, y);

    doc.setDrawColor(40, 167, 69);
    doc.line(15, y + 2, 195, y + 2);

    y += 12;

    Object.entries(results).forEach(([key, value], index) => {
      const rawVal = Array.isArray(value)
        ? value[1]
        : String(value);

      const cleanKey = String(key)
        .replace(/["']/g, '')
        .trim();

      const cleanValue = String(rawVal)
        .replace(/["']/g, '')
        .trim();

      const keyLines = doc.splitTextToSize(cleanKey, 70);
      const valueLines = doc.splitTextToSize(cleanValue, 80);

      const rowHeight =
        Math.max(keyLines.length, valueLines.length) * 6 + 6;

      if (y + rowHeight > 270) {
        doc.addPage();
        y = 20;
      }

      // alternating background
      if (index % 2 === 0) {
        doc.setFillColor(245, 245, 245);
      } else {
        doc.setFillColor(255, 255, 255);
      }

      doc.roundedRect(
        15,
        y - 4,
        180,
        rowHeight,
        2,
        2,
        'F'
      );

      // key
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(40, 40, 40);
      doc.text(keyLines, 20, y + 2);

      // value
      const color = getStatusColor(cleanValue);

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(
        color[0],
        color[1],
        color[2]
      );

      doc.text(valueLines, 105, y + 2);

      y += rowHeight + 3;
    });

    // ==========================
    // SUMMARY BOX
    // ==========================

    if (y + 25 < 270) {
      y += 8;

      doc.setFillColor(240, 248, 255);

      doc.roundedRect(
        15,
        y,
        180,
        18,
        3,
        3,
        'F'
      );

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 102, 204);
      doc.setFontSize(11);

      doc.text(
        'Generated automatically by WattQuick Calculator Suite',
        20,
        y + 11
      );
    }

    // ==========================
// ADD TOOLS PAGE
// ==========================

doc.addPage();

doc.setFillColor(0, 102, 204);
doc.rect(0, 0, pageWidth, 25, 'F');

doc.setFont('helvetica', 'bold');
doc.setFontSize(18);
doc.setTextColor(255, 255, 255);
doc.text('Explore More PDF Tools', 20, 16);

// SEO text
doc.setFont('helvetica', 'normal');
doc.setFontSize(10);
doc.setTextColor(90, 90, 90);

doc.text(
  'Free PDF Converter, Merger, Splitter, Compressor and Security Tools',
  20,
  32
);

const toolCategories = [
  {
    title: 'Convert & Edit',
    tools: [
      { name: 'Word to PDF', url: 'https://joinmypdf.com/word-to-pdf' },
      { name: 'Excel to PDF', url: 'https://joinmypdf.com/excel-to-pdf' },
      { name: 'PowerPoint to PDF', url: 'https://joinmypdf.com/powerpoint-to-pdf' },
      { name: 'Merge PDF', url: 'https://joinmypdf.com/merge-pdf' },
      { name: 'Split PDF', url: 'https://joinmypdf.com/split-pdf' },
      { name: 'Compress PDF', url: 'https://joinmypdf.com/compress-pdf' },
      { name: 'Rotate PDF', url: 'https://joinmypdf.com/rotate-pdf' },
    ],
  },
  {
    title: 'Security & Legal',
    tools: [
      { name: 'Protect PDF', url: 'https://joinmypdf.com/protect-pdf' },
      { name: 'Unlock PDF', url: 'https://joinmypdf.com/unlock-pdf' },
      { name: 'Redact PDF', url: 'https://joinmypdf.com/redact-pdf' },
      { name: 'Sign PDF', url: 'https://joinmypdf.com/sign-pdf' },
      { name: 'Invoice Generator', url: 'https://joinmypdf.com/invoice-generator' },
      { name: 'Data Converter', url: 'https://joinmypdf.com/data-converter' },
    ],
  },
];

const cardWidth = 80;
const cardHeight = 90;

toolCategories.forEach((cat, index) => {
  const x = index === 0 ? 15 : 110;
  const y = 45;

  doc.setFillColor(248, 249, 250);
  doc.roundedRect(
    x,
    y,
    cardWidth,
    cardHeight,
    3,
    3,
    'F'
  );

  doc.setDrawColor(220, 220, 220);

  doc.roundedRect(
    x,
    y,
    cardWidth,
    cardHeight,
    3,
    3
  );

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(0, 102, 204);

  doc.text(
    cat.title,
    x + 5,
    y + 10
  );

  let toolY = y + 20;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  cat.tools.forEach((tool) => {
    doc.setTextColor(60, 60, 60);

    doc.text(
      `• ${tool.name}`,
      x + 5,
      toolY
    );

    doc.link(
      x + 5,
      toolY - 5,
      65,
      6,
      {
        url: tool.url,
      }
    );

    toolY += 9;
  });
});

// CTA Box

doc.setFillColor(230, 244, 255);

doc.roundedRect(
  15,
  145,
  180,
  35,
  3,
  3,
  'F'
);

doc.setFont('helvetica', 'bold');
doc.setFontSize(14);
doc.setTextColor(0, 102, 204);

doc.text(
  'Need more PDF tools?',
  20,
  160
);

doc.setFont('helvetica', 'normal');
doc.setFontSize(11);
doc.setTextColor(80, 80, 80);

doc.text(
  'Visit JoinMyPDF.com for dozens of free PDF utilities.',
  20,
  170
);

doc.link(
  20,
  150,
  120,
  25,
  {
    url: 'https://joinmypdf.com',
  }
);

// Footer פעם אחת בסוף בלבד
addFooter(doc);

    const pdfBuffer = Buffer.from(
      doc.output('arraybuffer')
    );

    return new NextResponse(pdfBuffer, {
  status: 200,
  headers: {
    'Content-Type': 'application/pdf',
    'Content-Disposition':
      'attachment; filename="report.pdf"',
    ...headers,
  },
});
  } catch (error) {
    console.error(error);

    return NextResponse.json(
  {
    error: 'Failed to generate PDF',
  },
  {
    status: 500,
    headers,
  }
);
  }
}
